/**
 * CORETIMER Interrupt Handler
 * Routes the Core Timer interrupt vector to the plib handler.
 *
 * Generated by XC Project Importer — do not edit directly.
 * Device: {{DEVICE}}
 * SYSCLK: {{SYSCLK_HZ}} Hz
 */

#include <xc.h>
#include <sys/attribs.h>
#include "peripheral/plib_coretimer.h"

void __attribute__((used)) __ISR(_CORE_TIMER_VECTOR, ipl7SRS) CORE_TIMER_Handler(void)
{
    CORE_TIMER_InterruptHandler();
}
