/**
 * CORETIMER Peripheral Library
 * PIC32 MIPS Core Timer (CP0 COUNT register)
 *
 * The Core Timer runs at SYSCLK / 2 on all PIC32 devices (MX and MZ).
 *
 * Generated by XC Project Importer — do not edit directly.
 * Device: {{DEVICE}}
 * SYSCLK: {{SYSCLK_HZ}} Hz
 */

#ifndef PLIB_CORETIMER_H
#define PLIB_CORETIMER_H

#include <stdint.h>
#include <stdbool.h>
#include <xc.h>

#ifdef __cplusplus
    extern "C" {
#endif

/* Core Timer runs at half the system clock on all PIC32 variants */
#define CORE_TIMER_FREQUENCY    ({{SYSCLK_HZ}}UL / 2UL)

/* Periodic interrupt compare increment (period in ms, set by project config) */
#define CORE_TIMER_PERIOD_MS    {{CT_PERIOD_MS}}UL
#define CORE_TIMER_COMPARE_INC  (CORE_TIMER_FREQUENCY / 1000UL * CORE_TIMER_PERIOD_MS)

typedef void (*CORETIMER_CALLBACK)(uint32_t status, uintptr_t context);

typedef struct
{
    CORETIMER_CALLBACK  callback;
    uintptr_t           context;
} CORETIMER_OBJECT;

void     CORETIMER_Initialize(void);
void     CORETIMER_CallbackSet(CORETIMER_CALLBACK callback, uintptr_t context);
uint32_t CORETIMER_FrequencyGet(void);
void     CORETIMER_Start(void);
void     CORETIMER_Stop(void);
uint32_t CORETIMER_CounterGet(void);
void     CORETIMER_CompareSet(uint32_t compare);
void     CORETIMER_DelayMs(uint32_t delay_ms);
void     CORETIMER_DelayUs(uint32_t delay_us);
void     CORE_TIMER_InterruptHandler(void);

#ifdef __cplusplus
}
#endif

#endif /* PLIB_CORETIMER_H */