/**
 * CORETIMER Peripheral Library
 * PIC32 MIPS Core Timer (CP0 COUNT register)
 *
 * The Core Timer runs at SYSCLK / 2 on all PIC32 devices (MX and MZ).
 *
 * Generated by XC Project Importer — do not edit directly.
 * Device: {{DEVICE}}
 * SYSCLK: {{SYSCLK_HZ}} Hz
 */

#include "plib_coretimer.h"

static volatile CORETIMER_OBJECT coreTmr;

void CORETIMER_Initialize(void)
{
    // Disable Timer by setting Disable Count (DC) bit
    _CP0_SET_CAUSE(_CP0_GET_CAUSE() | _CP0_CAUSE_DC_MASK);
    coreTmr.callback = NULL;
}

void CORETIMER_CallbackSet(CORETIMER_CALLBACK callback, uintptr_t context)
{
    coreTmr.callback = callback;
    coreTmr.context = context;
}

void CORETIMER_Start(void)
{
    // Disable Timer by setting Disable Count (DC) bit
    _CP0_SET_CAUSE(_CP0_GET_CAUSE() | _CP0_CAUSE_DC_MASK);
    // Disable Interrupt
    IEC0CLR = 0x1;
    // Clear Core Timer
    _CP0_SET_COUNT(0);
    _CP0_SET_COMPARE(CORE_TIMER_COMPARE_INC);
    // Enable Timer by clearing Disable Count (DC) bit
    _CP0_SET_CAUSE(_CP0_GET_CAUSE() & (~_CP0_CAUSE_DC_MASK));
    // Enable Interrupt
    IEC0SET = 0x1;
}

void CORETIMER_Stop(void)
{
    // Disable Timer by setting Disable Count (DC) bit
    _CP0_SET_CAUSE(_CP0_GET_CAUSE() | _CP0_CAUSE_DC_MASK);
    // Disable Interrupt
    IEC0CLR = 0x1;
}

uint32_t CORETIMER_FrequencyGet(void)
{
    return (CORE_TIMER_FREQUENCY);
}

void CORETIMER_CompareSet(uint32_t compare)
{
    _CP0_SET_COMPARE(compare);
}

uint32_t CORETIMER_CounterGet(void)
{
    return _CP0_GET_COUNT();
}

void __attribute__((used)) CORE_TIMER_InterruptHandler(void)
{
    /* Advance compare register for next periodic interrupt */
    _CP0_SET_COMPARE(_CP0_GET_COMPARE() + CORE_TIMER_COMPARE_INC);
    uint32_t status = IFS0bits.CTIF;
    IFS0CLR = 0x1;
    if (coreTmr.callback != NULL)
    {
        uintptr_t context = coreTmr.context;
        coreTmr.callback(status, context);
    }
}

void CORETIMER_DelayMs(uint32_t delay_ms)
{
    uint32_t startCount, endCount;

    /* Calculate the end count for the given delay */
    endCount = (CORE_TIMER_FREQUENCY / 1000U) * delay_ms;

    startCount = _CP0_GET_COUNT();
    while ((_CP0_GET_COUNT() - startCount) < endCount)
    {
        /* Wait */
    }
}

void CORETIMER_DelayUs(uint32_t delay_us)
{
    uint32_t startCount, endCount;

    /* Calculate the end count for the given delay */
    endCount = (CORE_TIMER_FREQUENCY / 1000000U) * delay_us;

    startCount = _CP0_GET_COUNT();
    while ((_CP0_GET_COUNT() - startCount) < endCount)
    {
        /* Wait */
    }
}
