/**
 * Dynamic Makefile Generator
 * Generates Makefiles based on imported project structure
 */

import * as fs from 'fs';
import * as path from 'path';
import { ProjectInfo } from './projectImporter';

export interface MakefileOptions {
    projectInfo: ProjectInfo;
    outputPath: string;
    makeToolPath?: string;  // Custom make.exe path
    optimizationLevel?: string;  // -O0, -O1, -O2, -O3, -Os
    makePath?: string;  // Path to bundled make.exe
    binPath?: string;   // Path to bundled bin directory
    shPath?: string;    // Path to bundled sh.exe
}

export class MakefileGenerator {
    /**
     * Generate root Makefile and srcs/Makefile
     */
    async generate(options: MakefileOptions): Promise<void> {
        const { projectInfo, outputPath } = options;

        // Create output directories
        if (!fs.existsSync(outputPath)) {
            fs.mkdirSync(outputPath, { recursive: true });
        }

        const srcsDir = path.join(outputPath, 'srcs');
        if (!fs.existsSync(srcsDir)) {
            fs.mkdirSync(srcsDir, { recursive: true });
        }

        // Generate root Makefile from template
        const rootMakefile = await this.generateFromTemplate('RootMakefile.template', projectInfo, options);
        fs.writeFileSync(path.join(outputPath, 'Makefile'), rootMakefile);

        // Copy srcs/Makefile template (it's static with dynamic discovery)
        const srcsMakefile = await this.generateFromTemplate('SrcsMakefile.template', projectInfo, options);
        fs.writeFileSync(path.join(srcsDir, 'Makefile'), srcsMakefile);
    }

    /**
     * Generate Makefile content from template with variable substitution
     */
    private async generateFromTemplate(
        templateName: string,
        projectInfo: ProjectInfo,
        options: MakefileOptions
    ): Promise<string> {
        // Find template file - __dirname points to out/ after compilation
        const templatePath = path.join(__dirname, 'templates', 'xc32', templateName);
        
        if (!fs.existsSync(templatePath)) {
            throw new Error(`Template not found: ${templatePath}`);
        }

        let content = fs.readFileSync(templatePath, 'utf-8');

        // Replace bundled tools paths (used by both Makefiles)
        const makePath = options.makePath || 'make';
        const binPath = (options.binPath || '').replace(/\\/g, '/');
        const shPath = (options.shPath || '').replace(/\\/g, '/');
        
        content = content.replace(/\{\{MAKE_COMMAND\}\}/g, makePath);
        content = content.replace(/\{\{MAKE_BIN_DIR\}\}/g, binPath);
        content = content.replace(/\{\{SH_PATH\}\}/g, shPath);

        // Replace template variables
        content = content.replace(/\{\{PROJECT_NAME\}\}/g, projectInfo.projectName);
        content = content.replace(/\{\{DEVICE_NAME\}\}/g, projectInfo.deviceName);
        content = content.replace(/\{\{DEVICE_PART\}\}/g, projectInfo.deviceName);
        content = content.replace(/\{\{XC32_COMPILER_BIN\}\}/g, projectInfo.compilerBinDir || '');
        content = content.replace(/\{\{DFP_PATH\}\}/g, projectInfo.dfpPath || '');
        content = content.replace(/\{\{HEAP_SIZE\}\}/g, projectInfo.heapSize || '50000');
        content = content.replace(/\{\{STACK_SIZE\}\}/g, projectInfo.stackSize || '4096');
        content = content.replace(/\{\{OPT_LEVEL\}\}/g, options.optimizationLevel || '-O2');
        content = content.replace(/\{\{USE_MIKROE_BOOTLOADER\}\}/g, 'no');  // Default to no bootloader
        content = content.replace(/\{\{EXTRA_CFLAGS\}\}/g, (projectInfo.cflags || []).join(' '));
        content = content.replace(/\{\{EXTRA_LDFLAGS\}\}/g, (projectInfo.ldflags || []).join(' '));

        return content;
    }

    private generateRootMakefile(options: MakefileOptions): string {
        const { projectInfo } = options;
        const compiler = projectInfo.compiler.toLowerCase().includes('xc32') ? 'xc32' : 'gcc';

        return `#
# Root Makefile for ${projectInfo.projectName}
# Generated by PIC32-IDE-VSCode
#

PROJECT_NAME = ${projectInfo.projectName}
DEVICE = ${projectInfo.deviceName}

# Directories
SRCS_DIR = srcs
OBJS_DIR = objs
BINS_DIR = bins
INCS_DIR = incs

# Compiler
ifeq ($(OS),Windows_NT)
    COMPILER_PREFIX = xc32-
    RM = del /Q /F
    RMDIR = rmdir /S /Q
    MKDIR = if not exist "$(1)" mkdir "$(1)"
else
    COMPILER_PREFIX = xc32-
    RM = rm -f
    RMDIR = rm -rf
    MKDIR = mkdir -p $(1)
endif

CC = \${COMPILER_PREFIX}gcc
LD = \${COMPILER_PREFIX}gcc
AR = \${COMPILER_PREFIX}ar
OBJCOPY = \${COMPILER_PREFIX}objcopy
SIZE = \${COMPILER_PREFIX}size

# Output
ELF_FILE = \${BINS_DIR}/\${PROJECT_NAME}.elf
HEX_FILE = \${BINS_DIR}/\${PROJECT_NAME}.hex
MAP_FILE = \${BINS_DIR}/\${PROJECT_NAME}.map

# Default target
all: \${HEX_FILE}
\t@echo Build complete!

# Build sources
\${OBJS_DIR}:
\t@\$(call MKDIR,\${OBJS_DIR})

\${BINS_DIR}:
\t@\$(call MKDIR,\${BINS_DIR})

# Build object files
objs: \${OBJS_DIR}
\t@\${MAKE} -C \${SRCS_DIR}

# Link
\${ELF_FILE}: objs \${BINS_DIR}
\t@echo Linking \${PROJECT_NAME}...
\t@\${LD} -mprocessor=\${DEVICE} -o \${ELF_FILE} \\
\t\t\${OBJS_DIR}/*.o \\
\t\t-Wl,--defsym=_min_heap_size=0x1000 \\
\t\t-Wl,-Map=\${MAP_FILE}
\t@\${SIZE} \${ELF_FILE}

# Generate HEX
\${HEX_FILE}: \${ELF_FILE}
\t@echo Creating HEX file...
\t@\${OBJCOPY} -O ihex \${ELF_FILE} \${HEX_FILE}

# Clean
clean:
\t@echo Cleaning...
\t@\${MAKE} -C \${SRCS_DIR} clean
\t-@\$(RM) \${BINS_DIR}/*.elf \${BINS_DIR}/*.hex \${BINS_DIR}/*.map 2>nul

# Flash (requires bootloader)
flash: \${HEX_FILE}
\t@echo Flashing \${HEX_FILE}...
\t@mikro_hb "\${HEX_FILE}"

.PHONY: all objs clean flash
`;
    }

    private generateSrcsMakefile(options: MakefileOptions): string {
        const { projectInfo } = options;
        const optimization = options.optimizationLevel || '-O2';

        // Get relative source file paths
        const sourceFiles = projectInfo.sourceFiles.map(f => 
            path.relative(path.join(options.outputPath, 'srcs'), f).replace(/\\/g, '/')
        );

        // Generate object file list
        const objectFiles = sourceFiles.map(src => {
            const basename = path.basename(src, path.extname(src));
            return `\${OBJS_DIR}/${basename}.o`;
        }).join(' \\\n\t');

        // Generate include paths
        const includePaths = projectInfo.includePaths.map(p => 
            `-I"${p.replace(/\\/g, '/')}"`
        ).join(' \\\n\t');

        // Generate defines
        const defines = Array.from(projectInfo.defines.entries()).map(([key, value]) =>
            value ? `-D${key}=${value}` : `-D${key}`
        ).join(' \\\n\t');

        return `#
# Sources Makefile for ${projectInfo.projectName}
# Generated by PIC32-IDE-VSCode
#

OBJS_DIR = ../objs

# Compiler flags
CFLAGS = -mprocessor=\${DEVICE} \\
\t${optimization} \\
\t-ffunction-sections \\
\t-fdata-sections \\
\t-Wall \\
\t${includePaths}${defines ? '\\\n\t' + defines : ''}

# Source files
SOURCES = \\
\t${sourceFiles.join(' \\\n\t')}

# Object files
OBJECTS = ${objectFiles}

# Rules
all: \${OBJECTS}

# Compile C files
\${OBJS_DIR}/%.o: %.c
\t@echo Compiling $<...
\t@\${CC} \${CFLAGS} -c $< -o $@

# Compile assembly files
\${OBJS_DIR}/%.o: %.S
\t@echo Assembling $<...
\t@\${CC} \${CFLAGS} -c $< -o $@

clean:
\t@echo Cleaning objects...
\t-@\$(RM) \${OBJS_DIR}/*.o 2>nul

.PHONY: all clean
`;
    }
}
